# Base image
FROM mcr.microsoft.com/devcontainers/python:3.11-bookworm

# Install additional tools
RUN pip install --upgrade pip

# Set the user to vscode
USER vscode

# Set the working directory
WORKDIR /workspace
